### ISSUE TITLE
AMD Failure 

### ISSUE THREAD

**Issue by PaRoxUs** [seiyria/bootstrap-slider#194]
I get this error when I updated Bootstrap-slider from 3.0 to 4.0.

Uncaught TypeError: undefined is not a function bootstrap-slider.js:1173 ($.bridget(namespace, Slider);)
